# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# Build our cassandra and cassandra_seed host groups
- name: Create cassandra and cassandra_seed host groups
  hosts: "{{host_inventory}}"
  gather_facts: no
  tasks:
    # load the 'local variables file', if one was defined, to get any variables
    # we might need from that file when constructing our host groups
    - name: Load local variables file
      include_vars:
        file: "{{local_vars_file}}"
      when: not (local_vars_file is undefined or local_vars_file is none or local_vars_file | trim == '')
    # then, build our host groups
    - include_role:
        name: build-app-host-groups
      vars:
        host_group_list:
          - { name: cassandra, role: seed, invert_match: true }
          - { name: cassandra, role: seed }
      when: inventory_type == 'dynamic'
    - include_role:
        name: build-app-host-groups
      vars:
        host_group_list:
          - { name: cassandra, node_list: "{{host_inventory | difference(cassandra_seed_nodes | default([]))}}" }
          - { name: cassandra_seed, node_list: "{{cassandra_seed_nodes | default([])}}" }
      when: inventory_type == 'static'
    - set_fact:
        cassandra_nodes: "{{cassandra_nodes | difference(groups['cassandra_skip'] | default([]))}}"
      when: (groups['cassandra_skip'] | default([])) != []

# Then, deploy Cassandra to the nodes in the cassandra_seed host group
- name: Install/configure servers (seed nodes)
  hosts: cassandra_seed:&cassandra_seed_nodes
  gather_facts: no
  vars_files:
    - vars/cassandra.yml
  vars:
    - combined_package_list: "{{ (default_packages|default([])) | union(cassandra_package_list) | union((install_packages_by_tag|default({})).cassandra|default([])) }}"
  tasks:
    - include: provisioning-tasks.yml static=no

# Once the seed nodes have been deployed, repeat the same process to deploy Cassandra to the non-seed
# nodes (configuring them to talk with the seed nodes)
- name: Install/configure servers (non-seed nodes)
  hosts: cassandra:&cassandra_nodes
  gather_facts: no
  vars_files:
    - vars/cassandra.yml
  vars:
    - combined_package_list: "{{ (default_packages|default([])) | union(cassandra_package_list) | union((install_packages_by_tag|default({})).cassandra|default([])) }}"
  tasks:
    - include: provisioning-tasks.yml static=no
