# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include: update-linux-settings.yml static=no
- include: add-cassandra-user.yml static=no
- include: install-apache-cassandra.yml static=no
- include: configure-cassandra-nodes.yml static=no
- include: create-cassandra-services.yml static=no
- include: start-cassandra-services.yml static=no
